# Settings
settings:
  interval: 5 # in seconds
  log_path: logs/test.log

# ClickHouse credentials
clickhouse:
 db: default
 table: access_logs
 host: 127.0.0.1
 port: 8123
 credentials:
  user: default
  password:
 columns:
  remoteAddr: remote_addr
  remoteUser: remote_user
# NGINX
nginx:
  log_type: main
  log_format: $remote_addr - $remote_user [$time_local] "$request" $status $bytes_sent "$http_referer" "$http_user_agent"
